# Generated by Django 4.0.5 on 2022-06-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['answer']},
        ),
    ]
